### ISSUE TITLE
Update preprint link to PLOS ONE article

### ISSUE THREAD

**Issue by stain** [ISA-tools/soapdenovo2#23]
"Overview" under http://isa-tools.github.io/soapdenovo2/ embeds&links to the [biorxiv preprint](http://biorxiv.org/content/early/2014/12/08/011973) - but this should be updated to point to the published [PLOS ONE paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0127612) and its DOI [10.1371/journal.pone.0127612](http://dx.doi.org/10.1371/journal.pone.0127612)

**Comment by stain** [comment]
Perhaps the DOI should appear in the RDF as well as an annotation?

**Comment by agbeltran** [comment]
Thank you Stian. We will incorporate this.
